CONFIG_ZMK_BACKLIGHT=y
CONFIG_LED=y
CONFIG_IS31FL3731=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=4000

# Enable the external power control subsystem
CONFIG_ZMK_EXT_POWER=y
CONFIG_LOG_MODE_IMMEDIATE=y

